name: backend-cicd
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - uses: actions/checkout@v3 
      - name: Install dependencies & Tests
        run: |
          npm install
          npm test
  cd:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -i ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build
        run: docker build -t back.
      - name: Add tags
        run: |
          docker tag back ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker tag back ${{ secrets.DOCKER_USER }}/back:latest
      - name: Push docker image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/back:latest
